name: macos

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    uses: ./.github/workflows/test.yml
    with:
      os: macos-latest
