name: ubuntu

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ubuntu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
