name: windows

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows-latest
